function [BW,maskedImage] = segmentImagev3(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 01-May-2022
%----------------------------------------------------


% Auto clustering
s = rng;
rng('default');
L = imsegkmeans(single(X),2,'NumAttempts',2);
rng(s);
BW = L == 2;

% Invert mask
BW = imcomplement(BW);

% Open mask with disk
radius = 6;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Erode mask with disk
radius = 6;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Invert mask
BW = imcomplement(BW);

% Clear borders
BW = imclearborder(BW);

% Erode mask with disk
radius = 8;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Dilate mask with disk
radius = 8;
decomposition = 8;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

