function [BW,maskedImage] = segmentImagev4(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 01-May-2022
%----------------------------------------------------


% Threshold image - adaptive threshold
BW = imbinarize(X, 'adaptive', 'Sensitivity', 0.500000, 'ForegroundPolarity', 'dark');

% Erode mask with disk
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Dilate mask with rectangle
dimensions = [10 10];
se = strel('rectangle', dimensions);
BW = imdilate(BW, se);

% Close mask with rectangle
dimensions = [10 10];
se = strel('rectangle', dimensions);
BW = imclose(BW, se);

% Erode mask with rectangle
dimensions = [23 10];
se = strel('rectangle', dimensions);
BW = imerode(BW, se);

% Open mask with rectangle
dimensions = [5 10];
se = strel('rectangle', dimensions);
BW = imopen(BW, se);

% Dilate mask with rectangle
dimensions = [5 10];
se = strel('rectangle', dimensions);
BW = imdilate(BW, se);

% Invert mask
BW = imcomplement(BW);

% Clear borders
BW = imclearborder(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

