function [BW,maskedImage] = segmentImagev1(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 30-Apr-2022
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(X);

% Invert mask
BW = imcomplement(BW);

% Open mask with disk
radius = 13;
decomposition = 6;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Close mask with disk
radius = 13;
decomposition = 6;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Invert mask
BW = imcomplement(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

